[functions]

  [functions._ipx]
  node_bundler = "nft"

  [functions.___netlify-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    "dist\\apps\\next-test\\.next/server/**",
    "dist\\apps\\next-test\\.next/serverless/**",
    "dist\\apps\\next-test\\.next/*.json",
    "dist\\apps\\next-test\\.next/BUILD_ID",
    "dist\\apps\\next-test\\.next/static/chunks/webpack-middleware*.js",
    "!dist\\apps\\next-test\\.next/server/**/*.js.nft.json",
    "!../../node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions.___netlify-odb-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    "dist\\apps\\next-test\\.next/server/**",
    "dist\\apps\\next-test\\.next/serverless/**",
    "dist\\apps\\next-test\\.next/*.json",
    "dist\\apps\\next-test\\.next/BUILD_ID",
    "dist\\apps\\next-test\\.next/static/chunks/webpack-middleware*.js",
    "!dist\\apps\\next-test\\.next/server/**/*.js.nft.json",
    "!../../node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

[build]
command = "nx build next-test"
publish = "dist/apps/next-test/.next"

  [build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200

[[redirects]]
from = "/cache/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/server/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/serverless/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/trace"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/traces"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/routes-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/build-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/prerender-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/react-loadable-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/BUILD_ID"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/api"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = true

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/_next/data/QshYUScFukmrdoOaw0Wxq/index.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[context]

  [context.production]

    [context.production.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.production.functions]

      [context.production.functions._ipx]
      node_bundler = "nft"

      [context.production.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "dist\\apps\\next-test\\.next/server/**",
        "dist\\apps\\next-test\\.next/serverless/**",
        "dist\\apps\\next-test\\.next/*.json",
        "dist\\apps\\next-test\\.next/BUILD_ID",
        "dist\\apps\\next-test\\.next/static/chunks/webpack-middleware*.js",
        "!dist\\apps\\next-test\\.next/server/**/*.js.nft.json",
        "!../../node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.production.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "dist\\apps\\next-test\\.next/server/**",
        "dist\\apps\\next-test\\.next/serverless/**",
        "dist\\apps\\next-test\\.next/*.json",
        "dist\\apps\\next-test\\.next/BUILD_ID",
        "dist\\apps\\next-test\\.next/static/chunks/webpack-middleware*.js",
        "!dist\\apps\\next-test\\.next/server/**/*.js.nft.json",
        "!../../node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.production.build]

      [context.production.build.environment]
      NEXT_PRIVATE_TARGET = "server"

    [[context.production.redirects]]
    from = "/_next/static/*"
    to = "/static/:splat"
    status = 200

    [[context.production.redirects]]
    from = "/_next/image*"
    to = "/_ipx/w_:width,q_:quality/:url"
    status = 301

      [context.production.redirects.query]
      url = ":url"
      w = ":width"
      q = ":quality"

    [[context.production.redirects]]
    from = "/_ipx/*"
    to = "/.netlify/builders/_ipx"
    status = 200

    [[context.production.redirects]]
    from = "/cache/*"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/server/*"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/serverless/*"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/trace"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/traces"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/routes-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/build-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/prerender-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/react-loadable-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/BUILD_ID"
    to = "/404.html"
    status = 404
    force = true

    [[context.production.redirects]]
    from = "/api"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.production.redirects]]
    from = "/api/*"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.production.redirects]]
    from = "/*"
    to = "/.netlify/functions/___netlify-handler"
    status = 200
    force = true

      [context.production.redirects.conditions]
      Cookie = [
        "__prerender_bypass",
        "__next_preview_data"
      ]

    [[context.production.redirects]]
    from = "/_next/data/QshYUScFukmrdoOaw0Wxq/index.json"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.production.redirects]]
    from = "/"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.production.redirects]]
    from = "/*"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

  [context.master]

    [context.master.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.master.functions]

      [context.master.functions._ipx]
      node_bundler = "nft"

      [context.master.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "dist\\apps\\next-test\\.next/server/**",
        "dist\\apps\\next-test\\.next/serverless/**",
        "dist\\apps\\next-test\\.next/*.json",
        "dist\\apps\\next-test\\.next/BUILD_ID",
        "dist\\apps\\next-test\\.next/static/chunks/webpack-middleware*.js",
        "!dist\\apps\\next-test\\.next/server/**/*.js.nft.json",
        "!../../node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.master.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        "dist\\apps\\next-test\\.next/server/**",
        "dist\\apps\\next-test\\.next/serverless/**",
        "dist\\apps\\next-test\\.next/*.json",
        "dist\\apps\\next-test\\.next/BUILD_ID",
        "dist\\apps\\next-test\\.next/static/chunks/webpack-middleware*.js",
        "!dist\\apps\\next-test\\.next/server/**/*.js.nft.json",
        "!../../node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.master.build]

      [context.master.build.environment]
      NEXT_PRIVATE_TARGET = "server"

    [[context.master.redirects]]
    from = "/_next/static/*"
    to = "/static/:splat"
    status = 200

    [[context.master.redirects]]
    from = "/_next/image*"
    to = "/_ipx/w_:width,q_:quality/:url"
    status = 301

      [context.master.redirects.query]
      url = ":url"
      w = ":width"
      q = ":quality"

    [[context.master.redirects]]
    from = "/_ipx/*"
    to = "/.netlify/builders/_ipx"
    status = 200

    [[context.master.redirects]]
    from = "/cache/*"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/server/*"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/serverless/*"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/trace"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/traces"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/routes-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/build-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/prerender-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/react-loadable-manifest.json"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/BUILD_ID"
    to = "/404.html"
    status = 404
    force = true

    [[context.master.redirects]]
    from = "/api"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.master.redirects]]
    from = "/api/*"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.master.redirects]]
    from = "/*"
    to = "/.netlify/functions/___netlify-handler"
    status = 200
    force = true

      [context.master.redirects.conditions]
      Cookie = [
        "__prerender_bypass",
        "__next_preview_data"
      ]

    [[context.master.redirects]]
    from = "/_next/data/QshYUScFukmrdoOaw0Wxq/index.json"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.master.redirects]]
    from = "/"
    to = "/.netlify/functions/___netlify-handler"
    status = 200

    [[context.master.redirects]]
    from = "/*"
    to = "/.netlify/functions/___netlify-handler"
    status = 200